server.port=8080
eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# Route 1 - Employee Service
spring.cloud.gateway.server.webflux.routes[0].id=employeeservice
spring.cloud.gateway.server.webflux.routes[0].uri=lb://EmployeeService
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/employees/**

# Route 2 - Department Service
spring.cloud.gateway.server.webflux.routes[1].id=departmentservice
spring.cloud.gateway.server.webflux.routes[1].uri=lb://DepartmentService
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/departments/**
eureka.instance.prefer-ip-address=true
